---
title: "Asthma Brief V1"
author: "MikaylaBranz"
date: "9/7/2020"
output: html_document
---

```{r setup, include=TRUE, echo = False}
knitr::opts_chunk$set(echo = TRUE)
```
## Bring in the data
```{r}
#Install readr package to help import csv files
#install.packages("readr")

#Open readr package 
library(readr)

#Use readr to import csv files. 
asthma2014 <- read_csv("2014_Asthma.csv")
asthma2015 <- read_csv("2015_Asthma.csv")
asthma2016 <- read_csv("2016_Asthma.csv")
asthma2017 <- read_csv("2017_Asthma.csv")
asthma2018 <- read_csv("2018_Asthma.csv")
asthma2019 <- read_csv("2019_Asthma.csv")
asthma2020 <- read_csv("2020_Asthma_9-2.csv")
```
# Combine into 1 Dataset
```{r}
#load tidyverse
library(tidyverse)

#combine datasets

#make list of datasets to combine
asthmaAll <- list (asthma2014,
                asthma2015,
                asthma2016,
                asthma2017,
                asthma2018,
                asthma2019,
                asthma2020)

#combine elements in the list
asthma <- 
  asthmaAll %>%
  bind_rows()
```
# Trim dataset
```{r}
#select only variables that are relevant
asthma <- asthma %>% 
  select(Date, Zipcode,Age, Sex, Hospital,Race_flat,Ethnicity_Flat, HospitalName,HospitalZipCode,EssenceID, PIN, Time)

colnames(asthma)
```
# Clean Dataset
```{r}
#Separate "Date" into month, day, and year

asthma <- asthma %>%
  separate(col = Date, into = c("Month", "Day", "Year"), sep = "/", remove = FALSE)  

#Check and fix classes

class(asthma)
sapply(asthma,class)

asthma <- data.frame(asthma) 
asthma$Month <- as.numeric(asthma$Month)
asthma$Day <- as.numeric(asthma$Day)
asthma$Year <- as.numeric(asthma$Year)
asthma$Zipcode <- as.factor(asthma$Zipcode)
asthma$Age <- as.numeric(asthma$Age)
asthma$Sex <- as.factor(asthma$Sex)
asthma$Race_flat <- as.factor(asthma$Race_flat)
asthma$Ethnicity_Flat <- as.factor(asthma$Ethnicity_Flat)

#Recode Ethnicity
asthma <- asthma %>% 
  mutate(Ethnicity = recode(Ethnicity_Flat,
         ";Non-Hispanic;" = "NonHispanic", 
         ";NOT H;" = "NonHispanic", 
         ";Not H;" = "NonHispanic",
         ";Not Hispanic or Latino;" = "NonHispanic",
         
         ";Unknown;" = "UnknownOrNotReported",
         ";N;" = "UnknownOrNotReported", 
         ";U;" ="UnknownOrNotReported", 
         ";NR;" = "UnknownOrNotReported", 
         ";BL;" = "UnknownOrNotReported", 
         ";WH;" = "UnknownOrNotReported",
         
         ";Hispanic;" = "HispanicLatino",
         ";Hispa;" = "HispanicLatino", 
         ";H;" = "HispanicLatino",
         ";Hispanic or Latino;" = "HispanicLatino")) 


#Recode Race
asthma <- asthma %>% 
  mutate(Race = recode(Race_flat,
                       ";Black;" = "BlackOrAfricanAmerican",
                       ";B;" = "BlackOrAfricanAmerican",
                       ";Black or African American;" = "BlackOrAfricanAmerican",
                       ";Black or African American;Black or African American;" = "BlackOrAfricanAmerican",
                       
                       ";White;" = "White",
                       ";W;" = "White",
                       
                       ";Other;" = "Other",
                       ";Ameri;" = "Other",
                       ";O;" = "Other",
                       ";Other Race;" = "Other",
                       ";Other Race;Other Race;" = "Other",
                       
                       ";Unknown;" = "Unknown",
                       ";NR;" = "Unknown",
                       ";U;" = "Unknown",
                       
                       ";Asian or Pacific Islander;" = "AsianOrPacificIslander",
                       ";Asian;" = "AsianOrPacificIslander",
                       ";A;" = "AsianOrPacificIslander",
                       ";Native hawaiian or Other Pacific Islander;" = "AsianOrPacificIslander",
                       
                       ";American Indian or Alaskan Native;" = "AmericanIndianOrAlaskaNative",
                       ";Nativ;" = "AmericanIndianOrAlaskaNative",
                       ";American Indian or Alaska Native;" = "AmericanIndianOrAlaskaNative",
                       
                       ";M;" = "MixedRace",
                       ";White;Black or African American;" = "MixedRace",
                       ";Black or African American;White;" = "MixedRace",
                       ";Other Race;White;" = "MixedRace")) %>% 

  mutate(RaceCondensed = recode(Race, 
                               "BlackOrAfricanAmerican" = "Black",
                               "White" = "White",
                               "Other" = "Other",
                               "Unknown" = "Other",
                               "AsianOrPacificIslander" = "Other",
                               "AmericanIndianOrAlaskaNative" = "Other",
                               "MixedRace" = "Other"))

## Recode age into categories
#Remove case with impossible age (117)
asthma <- asthma %>% 
  filter(Age != "117")

asthma <- asthma %>% 
  mutate(AgeGroup =  if_else(Age %in% 0:9, "0-9",
                     ifelse(Age %in% 10:19, "10-19",
                     ifelse(Age %in% 20:29, "20-29",
                     ifelse(Age %in% 30:39, "30-39",
                     ifelse(Age %in% 40:49, "40-49",
                     ifelse(Age %in% 50:59, "50-59",
                     ifelse(Age %in% 60:69, "60-69",
                     ifelse(Age %in% 70:79, "70-79",
                     ifelse(Age >= 80, "80+", "NA"))))))))))


#remove any duplicates in data
asthma <- distinct(asthma, .keep_all = FALSE)
```
#Graph cases by Race
```{r}
library(ggplot2)
## Graph by number of cases


#change order of race
#check levels
levels(asthma$RaceCondensed)
#make a list with new order of levels
 newlevel <- c("Black", "White","Other")
 #change the order of the levels in race
 asthma$RaceCondensed <- factor(asthma$RaceCondensed, levels = newlevel)

#Graph the total number of cases by race, over time. Use categories "Black, White, and Other" Only include Jan-August so that it is comparable to 2020
asthma %>% 
  filter(Month < 9) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Year, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Year", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma-Related ER Visits by Race (Jan-Aug), 2014-2020")

#Graph the total number of cases by race, over time. Use all race categories. Only include Jan-August so that it is comparable to 2020
asthma %>% 
  filter(Month < 9) %>% 
  group_by(Race, Year) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Year, y = total, color = Race), size = 1) +
  labs(y="Cases", x = "Year", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma-Related ER Visits by Race (Jan-Aug), 2014-2020")

#Graph Race by Rate

#Import race populations
RacePopulation <- read_csv("RacePopulation.csv")

#Check and fix class of RacePopulation dataframe and Race variable
class(RacePopulation)
RacePopulation<-data.frame(RacePopulation)

class(RacePopulation$Race)
RacePopulation$Race<-as.factor(RacePopulation$Race)


#check and fix variable names to match
unique(RacePopulation$Race)
unique(asthma$Race)

RacePopulation$Race <- recode(RacePopulation$Race, "African American" = "Black", "Caucasian" = "White")

asthma <- asthma %>% 
  left_join(RacePopulation, by = c("RaceCondensed" = "Race")) %>% 
    rename("RacePop" = "Population")

#Graph asthma rates by race in 2019
asthma %>% 
  filter(Year == 2019) %>% 
  group_by(RaceCondensed) %>% 
  summarise(total = (10000* n()/(12*mean(RacePop)))) %>%
  ggplot() +
  geom_col(aes(x = RaceCondensed, y = total, fill = RaceCondensed)) +
  labs(y="Cases", x = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
   theme(panel.grid.minor.x=element_blank())+
   scale_fill_manual(values = c("darkorchid4","turquoise4", "#02075d")) +
    scale_y_continuous(expand = c(0,0), limits = c(0,11)) +
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2019")

#Graph asthma rates by race in 2020

asthma %>% 
  filter(Year == 2020) %>% 
  group_by(RaceCondensed) %>% 
  summarise(total = (10000* n()/(8*mean(RacePop)))) %>%
  ggplot() +
  geom_col(aes(x = RaceCondensed, y = total, fill = RaceCondensed)) +
  labs(y="Cases", x = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
   theme(panel.grid.minor.x=element_blank())+
  scale_fill_manual(values = c("darkorchid4","turquoise4", "#02075d")) +
  scale_y_continuous(expand = c(0,0), limits = c(0,11)) +
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2020")

#Graph asthma rates by race in 2019 and 2020
Asthma2019RaceRate <- data.frame(asthma %>% 
  filter(Year == 2019) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(total = (10000* n()/(12*mean(RacePop)))))

Asthma2020RaceRate <- data.frame(asthma %>% 
  filter(Year == 2020) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(total = (10000* n()/(8*mean(RacePop)))))

# Graph rates in 2019 and 2020, combined


#make list of datasets to combine
asthmaRaceAll <- list (Asthma2019RaceRate, Asthma2020RaceRate)

#Combine datasets
AsthmaRaceRate <- 
  asthmaRaceAll %>%
  bind_rows()

AsthmaRaceRate
class(AsthmaRaceRate)

sapply(AsthmaRaceRate, class)
AsthmaRaceRate$Year <-as.factor(AsthmaRaceRate$Year)


#Now graph them together
## for task force
AsthmaRaceRate %>% 
  ggplot() +
  geom_col(aes(x = Year, y=total, fill = RaceCondensed), position = "dodge") +
  labs(y="Cases per 10,000 people per month", x = "Year", fill = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
   theme(panel.grid.minor.x=element_blank())+
   scale_fill_manual(values = c("#D35400","#3498DB", "#566573")) +
    scale_y_continuous(expand = c(0,0), limits = c(0,11)) +
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2019 and 2020")


#Check on asthma ER Visits in 2020- do they drop off w/ covid?
asthma %>% 
  filter(Year == 2020 & Month < 9) %>% 
  group_by(RaceCondensed, Month) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Month, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Month", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(0,8, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma ER Visit Cases by Month, 2020")

#Check on asthma ER Visits in 2020 for children- do they drop off w/ covid?
asthma %>% 
  filter(Year == 2020 & AgeGroup == "0-9" & Month <9) %>% 
  group_by(RaceCondensed, Month) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Month, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Month", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(0,8, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("0-9 year olds Asthma ER Visit Cases by Month, 2020")

#Check on asthma ER Visits in 2019 for comparison
asthma %>% 
  filter(Year == 2019 | Year==2020) %>% 
  group_by(RaceCondensed, Month) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Month, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Month", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(0,12, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma ER Visit Cases by Month, 2019")

#Check on asthma ER Visits in 2019 of kids 0-9 for comparison
asthma %>% 
  filter(Year == 2019) %>% 
  group_by(RaceCondensed, Month) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = Month, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Month", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(0,12, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("0-9 Year olds Asthma ER Visit Cases by Month, 2019")

#Put both years together#Change Month to words
class(asthma$Month)
asthma$Month <- as.factor(asthma$Month)

asthma$Month <-recode(asthma$Month, "1" = "Jan", "2" = "Feb", "3" = "Mar", "4"= "Apr", "5" = "May", "6" = "Jun", "7" = "Jul", "8" = "Aug", "9" = "Sep", "10" = "Oct", "11" = "Nov", "12" = "Dec")

levels
#combine month and year
class(asthma$Year)
asthma$Year <- as.factor(asthma$Year)

asthma %>%  
  unite (col= "MonthYear",
         Month, Year, 
         sep = ". ", 
         remove =FALSE)

class(asthma$MonthYear)
asthma$MonthYear<- as.factor(asthma$MonthYear)

asthma %>% 
  filter(Year == 2019 | Year == 2020) %>% 
  group_by(RaceCondensed, MonthYear) %>% 
  summarise(total = n()) %>% 
  ggplot() +
   geom_line(aes(x = MonthYear, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Month", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(0,12, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma ER Visit Cases by Month, 2019-2020")

##change ER Visit to "ER visits", data source = essence. "preliminary"

```
##Graphs for task force
```{r}
#change order of race
#check levels
levels(asthma$RaceCondensed)
#make a list with new order of levels
 newlevel <- c("Black", "White","Other")
 #change the order of the levels in race
 asthma$RaceCondensed <- factor(asthma$RaceCondensed, levels = newlevel)
#Code for rate
RacePopulation <- read_csv("RacePopulation.csv")

#Check and fix class of RacePopulation dataframe and Race variable
class(RacePopulation)
RacePopulation<-data.frame(RacePopulation)

class(RacePopulation$Race)
RacePopulation$Race<-as.factor(RacePopulation$Race)


#check and fix variable names to match
unique(RacePopulation$Race)
unique(asthma$Race)

RacePopulation$Race <- recode(RacePopulation$Race, "African American" = "Black", "Caucasian" = "White")

asthma <- asthma %>% 
  left_join(RacePopulation, by = c("RaceCondensed" = "Race")) %>% 
    rename("RacePop" = "Population")

#Graph by race, year, and rate
asthma %>% 
  filter(Year < 2020) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(Total = n(), Pop = mean(RacePop), Rate = 1000*Total/Pop) %>% 
  ggplot() +
  geom_point(aes(x = Year, y = Rate, color = RaceCondensed), size = 3, shape = 4)+
   geom_line(aes(x = Year, y = Rate, color = RaceCondensed), size = 1) +
  labs(y="Cases per 1,000 People", x = "Year", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  scale_color_manual(values = c("darkorchid4","turquoise4", "red"))+
  ggtitle("Asthma-Related ER Visits by Race, 2014-2019")

#Try for kids 0-9

#change order of race
#check levels
levels(asthma$RaceCondensed)
#make a list with new order of levels
 newlevel <- c("Black", "White","Other")
 #change the order of the levels in race
 asthma$RaceCondensed <- factor(asthma$RaceCondensed, levels = newlevel)
#Code for rate
ChildrenRacePopulation <- read_csv("Under10RacePopulation.csv")

#Check and fix class of RacePopulation dataframe and Race variable
class(ChildrenRacePopulation)
ChildrenRacePopulation<-data.frame(ChildrenRacePopulation)

class(ChildrenRacePopulation$Race)
ChildrenRacePopulation$Race<-as.factor(ChildrenRacePopulation$Race)


#check and fix variable names to match
unique(ChildrenRacePopulation$Race)
unique(asthma$RaceCondensed)

ChildrenRacePopulation$Race <- recode(ChildrenRacePopulation$Race, "BlackOrAfricanAmerican" = "Black")

asthma <- asthma %>% 
  left_join(ChildrenRacePopulation, by = c("RaceCondensed" = "Race")) %>% 
    rename("Under10Pop" = "Under10Pop")

#Now graph for children 0-9
#Graph by race, year, and rate
asthma %>% 
  filter(Year < 2020 & Age < 10) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(Total = n(), Pop = mean(Under10Pop), Rate = 1000*Total/Pop) %>% 
  ggplot() +
  geom_point(aes(x = Year, y = Rate, color = RaceCondensed), size = 3, shape = 4)+
   geom_line(aes(x = Year, y = Rate, color = RaceCondensed), size = 1) +
  labs(y="Cases per 1,000 People", x = "Year", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  scale_color_manual(values = c("darkorchid4","turquoise4", "red"))+
  ggtitle("Asthma-Related ER Visits by Race for Children 0-9, 2014-2019")

```



```{r}
#Check the total number of cases by ethnicity, over time. Only include Jan-August so that it is comparable to 2020
asthma %>% 
  filter(Month < 9) %>% 
  group_by(Ethnicity, Year) %>% 
  summarise(total = n()) 
#There aren't really enough Latinx cases to be able to look at this as a proportion? 

#Graph the total number of cases by zipcode in 2019
asthma %>% 
  filter(Year==2019) %>% 
  group_by(Zipcode) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = reorder(Zipcode, -total), y= total, dodge = TRUE), fill= "Maroon") +
  theme(axis.text.x=element_text(angle=45, hjust=1), legend.position = "none") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,300)) +
  labs(y="Cases", x = "Zip Code")+
  ggtitle("Asthma ER Visit Cases by Zip Code, Jan.- Dec. 2019")

#Graph the total number of cases by zipcode in 2020
asthma %>% 
  filter(Year==2020 | Year==2019) %>% 
  group_by(Zipcode, Year) %>% 
  summarise(total = n()) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = reorder(Zipcode, -total), y= total, dodge = TRUE), fill = "Maroon") +
  theme(axis.text.x=element_text(angle=45,hjust=1,), legend.position = "none") +
    scale_y_continuous(expand = c(0,0), limits = c(0,150)) +
  labs(y="Cases", x = "Zip Code")+
  ggtitle("Asthma ER Visit Cases by Zip Code, Jan.-Aug. 2020")


 
 #Now figure out how to do it as a proportion of the population.


```


## Explore the data
```{r}

#Explore data by age group



#make AgeGroup factor variable
asthma$AgeGroup<-as.factor(asthma$AgeGroup)

asthma <- asthma %>% 
  mutate(AgeGroupPractical =  
                     if_else(Age %in% 0:5, "0-5",
                     ifelse(Age %in% 6:10, "6-10",
                     ifelse(Age %in% 11:14, "11-14",
                     ifelse(Age %in% 15:18, "15-18",
                     ifelse(Age %in% 19:26, "19-26",
                     ifelse(Age %in% 27:39, "27-39",
                     ifelse(Age %in% 40:59, "40-59",
                     ifelse(Age %in% 60:79, "60-79",
                     ifelse(Age >= 80, "80+", "NA"))))))))))

#make AgeGroup factor variable
asthma$AgeGroupPractical<-as.factor(asthma$AgeGroupPractical)

levels(asthma$AgeGroup)

#Graph the total number of cases by age group in 2019
asthma %>% 
  filter(Year==2019) %>% 
  group_by(AgeGroup) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = AgeGroup, y= total, dodge = TRUE), fill = "Navy") +
  theme(axis.text.x=element_text(angle=45,hjust=1,), legend.position = "none") +
  labs(y="Cases", x = "Age Group")+
  scale_y_continuous(expand = c(0,0), limits = c(0,450)) +
  ggtitle("Asthma ER Visit Cases by Age Group, Jan.-Dec. 2019")

#Graph the total number of cases by age group in 2020
asthma %>% 
  filter(Year==2020) %>% 
  group_by(AgeGroup) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = AgeGroup, y= total, dodge = TRUE), fill = "Navy") +
  theme(axis.text.x=element_text(angle=45,hjust=1,), legend.position = "none") +
  labs(y="Cases", x = "Age Group")+
 scale_y_continuous(expand = c(0,0), limits=c(0,200)) +
  ggtitle("Asthma ER Visit Cases by Age Group, Jan.-Aug 2020")

#Graph the total number of cases by practical age group in 2019
asthma %>% 
  filter(Year==2019) %>% 
  group_by(AgeGroupPractical) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = AgeGroupPractical, y= total, dodge = TRUE), fill = "Navy") +
  theme(axis.text.x=element_text(angle=45,hjust=1,), legend.position = "none") +
  labs(y="Cases", x = "Age Group")+
  scale_y_continuous(expand = c(0,0), limits = c(0,500)) +
  ggtitle("Asthma ER Visit Cases by Age Group, Jan.-Dec. 2019")

#Graph the total number of cases by age group in 2020
asthma %>% 
  filter(Year==2020) %>% 
  group_by(AgeGroupPractical) %>% 
summarise(total = n()) %>% 
  ggplot() +
   geom_col(aes(x = AgeGroupPractical, y= total, dodge = TRUE), fill = "Navy") +
  theme(axis.text.x=element_text(angle=45,hjust=1,), legend.position = "none") +
  labs(y="Cases", x = "Age Group")+
 scale_y_continuous(expand = c(0,0), limits=c(0,210)) +
  ggtitle("Asthma ER Visit Cases by Age Group, Jan.-Aug 2020")
       

```
```{r}
#Now to make proportions



#Age Group Proportions:

#Import Age Group populations
AgeGroupPopulation <- read_csv("AgeGroupPopulation.csv")

#Check and fix class of RacePopulation dataframe and Race variable
class(AgeGroupPopulation)
AgeGroupPopulation<-data.frame(AgeGroupPopulation)

class(AgeGroupPopulation$AgeGroup)
AgeGroupPopulation$AgeGroup<-as.factor(AgeGroupPopulation$AgeGroup)


#check and fix variable names to match
unique(AgeGroupPopulation$AgeGroup)
unique(asthma$AgeGroup)

class(AgeGroupPopulation$AgeGroup)

asthma <- asthma %>% 
  left_join(AgeGroupPopulation, by = "AgeGroup") %>% 
    rename("AgeGroupPop" = "Population")

#Ethnicity Proportions:

#Import Age Group populations
EthnicityPopulation <- read_csv("EthnicityPopulation.csv")

#Check and fix class of RacePopulation dataframe and Race variable
class(EthnicityPopulation)
EthnicityPopulation<-data.frame(EthnicityPopulation)

class(EthnicityPopulation$Ethnicity)
EthnicityPopulation$Ethnicity<-as.factor(EthnicityPopulation$Ethnicity)


#check and fix variable names to match
unique(EthnicityPopulation$Ethnicity)
unique(asthma$EthnicityCondensed)

class(EthnicityPopulation$Ethnicity)

asthma <- asthma %>% 
  mutate(EthnicityCondensed = recode(Ethnicity,
         "UnknownOrNotReported" = "NonHispanic")) 

EthnicityPopulation$Ethnicity <- recode(EthnicityPopulation$Ethnicity, "Non-Hispanic" = "NonHispanic", "Hispanic" = "HispanicLatino")
# wrong number

asthma <- asthma %>% 
  left_join(EthnicityPopulation, by = c("EthnicityCondensed" = "Ethnicity")) %>% 
    rename("EthnicityPop" = "Population")

asthma %>% 
  filter(Month < 9) %>% 
  group_by(EthnicityCondensed, Year) %>% 
  summarise(total = (10000* n()/(8*mean(EthnicityPop)))) %>%
  ggplot() +
   geom_line(aes(x = Year, y = total, color = EthnicityCondensed), size = 1) +
  labs(y="Cases", x = "Year", color = "Ethnicity") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Ethnicity, 2014-2020")

# NOTE: Sizes are probably too small for hispanic/latino to really be reasonable. Also, there are a LOT of unknowns, which got lumped into "not hispanic or latino" but are difficult to make meaningful conclusions from. I would NOT trust the analysis of ethnicity. 


```
```{r}
#Graph asthma rates by race over time
asthma %>% 
  filter(Month < 9) %>% 
  group_by(RaceCondensed, Year) %>% 
  summarise(total = (10000* n()/(8*mean(RacePop)))) %>%
  ggplot() +
   geom_line(aes(x = Year, y = total, color = RaceCondensed), size = 1) +
  labs(y="Cases", x = "Year", color = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
    scale_x_continuous(breaks = seq(2014,2020, by =1))+
   theme(panel.grid.minor.x=element_blank())+
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2014-2020")

#Graph asthma rates by race in 2020

asthma %>% 
  filter(Year == 2020) %>% 
  group_by(RaceCondensed) %>% 
  summarise(total = (10000* n()/(8*mean(RacePop)))) %>%
  ggplot() +
  geom_col(aes(x = RaceCondensed, y = total, fill = RaceCondensed)) +
  labs(y="Cases", x = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
   theme(panel.grid.minor.x=element_blank())+
  scale_fill_manual(values = c("darkorchid4","turquoise4", "#02075d")) +
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2020")

asthma %>% 
  filter(Year == 2019) %>% 
  group_by(RaceCondensed) %>% 
  summarise(total = (10000* n()/(12*mean(RacePop)))) %>%
  ggplot() +
  geom_col(aes(x = RaceCondensed, y = total, fill = RaceCondensed)) +
  labs(y="Cases", x = "Race") +
   theme(axis.text.x=element_text(angle=45,  hjust = 1)) +
   theme(panel.grid.minor.x=element_blank())+
   scale_fill_manual(values = c("darkorchid4","turquoise4", "#02075d")) +
  ggtitle("Asthma ER Visit Cases per 10,000 people per month, by Race, 2019")
```

```{r}
#Import age group population estimates
AgeGroupPopulation <- read_csv("AgeGroupPopulation.csv")

EthnicityPopulation <- read_csv("EthnicityPopulation.csv")
SexPopulation <- read_csv("SexPopulation.csv")
ZipcodePopulation <- read_csv("ZipcodePopulation.csv")

#Check and fix class

sapply(AgeGroupPopulation, class)
sapply(ZipcodePopulation, class)
sapply(RacePopulation, class)

left_join(AgeGroupPopulation, by = "AgeGroup") %>% 
   rename("AgePop" = "Population") %>%
```



```{r}


```
 
 